export let users = [
    {
        url: './Images/jane-austen.avif',
        name: "Jane",
        surname: "Austen",
        activity: ["Writer", "Novelist"],
        "birth-year": 1775,
    },
    {
        url: './Images/Malevich.jpeg',
        name: "Kazimir",
        surname: "Malevich",
        activity: ['Painter'],
        "birth-year": 1879,
    },
    {
        url: './Images/Henry-Ford.webp',
        name: "Henry",
        surname: "Ford",
        activity: ['Automobile manufacturer'],
        "birth-year": 1863,
    },
    {
        url: './Images/Steve.jfif',
        name: "Steve",
        surname: "Wozniak",
        activity: ['Programmer'],
        "birth-year": 1950,
    },
    {
        url: './Images/Ive.avif',
        name: "Jonahtan",
        surname: "Ive",
        activity: ['Designer'],
        "birth-year": 1967,
    },
    {
        url: './Images/bill.jfif',
        name: "Bill",
        surname: "Gates",
        activity: ['Businessman', 'Programmer'],
        "birth-year": 1955,
    },
    {
        url: './Images/jack.avif',
        name: "Jack",
        surname: "London",
        activity: ['Novelist'],
        "birth-year": 1876,
    },
    {
        url: './Images/coco.jfif',
        name: "Coco",
        surname: "Chanel",
        activity: ['Fashion designer'],
        "birth-year": 1883,
    },
    {
        url: './Images/picasso.jfif',
        name: "Pablo",
        surname: "Picasso",
        activity: ['Painter', 'Sculptor'],
        "birth-year": 1881,
    },
    {
        url: './Images/picasso.jfif',
        name: "Pablo",
        surname: "Picasso",
        activity: ['Painter', 'Sculptor'],
        "birth-year": 1881,
    }
]