let users = {
    user_1: {
        url: ,
        name: "Mahatma",
        surname: "Gandhi",
        age: ,
        job: ,
        isMarried: ,
    },
    user_2: {
        url: 'Images\Malevich.jpeg',
        name: "Kazimir",
        surname: "Malevich",
        age: ,
        job: 'painter',
        isMarried: ,
    },
    user_3: {
        url: '.\Images\Henry-Ford.webp',
        name: "Henry",
        surname: "Ford",
        age: ,
        job: ,
        isMarried: ,
    },
    user_4: {
        url: 'Images\Steve.jfif',
        name: "Steve",
        surname: "Wozniak",
        age: ,
        job: 'programmer',
        isMarried: ,
    },
    user_5: {
        url: 'Images\Ive.avif',
        name: "Jonahtan",
        surname: "Ive",
        age: ,
        job: 'designer',
        isMarried: ,
    },
    user_6: {
        url: 'Images\bill.jfif',
        name: "Bill",
        surname: "Gates",
        age: ,
        job: 'programmer',
        isMarried: ,
    },
    user_7: {
        url: 'Images\jack.avif',
        name: "Jack",
        surname: "London",
        age: ,
        job: 'writer',
        isMarried: ,
    },
    user_8: {
        url: 'Images\coco.jfif',
        name: "Coco",
        surname: "Chanel",
        age: ,
        job: 'designer',
        isMarried: ,
    },
    user_9: {
        url: 'Images\picasso.jfif',
        name: "Pablo",
        surname: "Picasso",
        age: ,
        job: 'painter',
        isMarried: ,
    }
}